---
- hosts: 172.31.31.139
  become: yes
  tasks:
     - name: i want to run linux command
       command: hostname -f
       register: myresult


     - name: i want display linux command output
       debug: 
          msg: "{{myresult}}"
