---
- hosts: webservernode
  become: yes
  tasks:
        - name: i want to install apache2 on ubuntu
          apt:
              name: "{[mywebserveronubuntu]}"
              state: present
          when: ansible_os_family=="Debian"

             
        - name: i want to start/stop apache2 on ubuntu node
          service:
             name: "{[mywebserveronubuntu]}"
             state: started
          when: ansible_os_family=="Debian"
           

        - name: i want to install webserver 0n redHad
          yum:
             name: "{[mywebserveronredhat]}"
             state: present
          when: ansible_os_family=="RedHat"

        - name: i want to start/stop apache2 on redhat node
          service:
             name:  "{[mywebserveronredhat]}"
             state: started
          when: ansible_os_family=="RedHat"