---
- hosts: all
  become: yes
  tasks:
        - name: i want to install apache2 on ubuntu
          apt:
              name: apache2
              state: present
              
        - name: i want to start/stop apache2 on ubuntu node
          service:
             name: apache2
             state: started
